"""Criando estrutura inicial

Revision ID: a6c93b5e29d4
Revises: 
Create Date: 2025-11-09 22:47:46.578685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c93b5e29d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('unidade_principal', sa.String(length=20), nullable=True),
    sa.Column('tipo_calculo', sa.String(length=50), nullable=True),
    sa.Column('parametros_requeridos', sa.String(length=500), nullable=True),
    sa.Column('consumo_medio_per_capita', sa.Float(), nullable=True),
    sa.Column('unidade_referencia', sa.String(length=10), nullable=True),
    sa.Column('periodo_referencia_dias', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('eventos_consumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('produto_base_id', sa.Integer(), nullable=True),
    sa.Column('data_evento', sa.DateTime(), nullable=True),
    sa.Column('tipo_evento', sa.String(length=50), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('unidade', sa.String(length=10), nullable=True),
    sa.Column('origem', sa.String(length=50), nullable=True),
    sa.Column('observacao', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['produto_base_id'], ['produtos_base.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('produto_base_id', sa.Integer(), nullable=False),
    sa.Column('parametros', sa.Text(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('unidade', sa.String(length=10), nullable=True),
    sa.Column('estoque_atual', sa.Float(), nullable=True),
    sa.Column('consumo_estimado_diario', sa.Float(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('data_validade', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['produto_base_id'], ['produtos_base.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_usuario')
    op.drop_table('eventos_consumo')
    op.drop_table('usuarios')
    op.drop_table('produtos_base')
    # ### end Alembic commands ###
